name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: actions/setup-flutter@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build app
        run: flutter build apk

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build/app/outputs/apk/debug/app-debug.apk
