name: Flutter CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build appbundle --release

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/apk/release/app-release.apk
     
